//La siguiente información fue la base de datos de mi proyecto.  
// Esta base de datos hace referencia a distintos tipos de envases y algunas de sus propiedades. 
// Como lo es un sku o id, categoria, nombre, material, capacidad, cuello, proveedor, lote, cantidad y un color. 

const data = [
    {
        sku: 1001,
        categoria: "Alimentos",
        nombre: "Garrafa Vinera",
        material: "PET",
        capacidad: "1750 ml",
        cuello: "28 mm",
        proveedor: "SoluPlast",
        lote: "5956",
        cantidad: 100,
        color: "Natural",
    },
    {
        sku: 1002,
        categoria: "Alimentos",
        nombre: "Potes Boca Ancha",
        material: "POLIETILENO",
        capacidad: "180 ml",
        cuello: "44 mm",
        proveedor: "SoluPlast",
        lote: "1232",
        cantidad: 50,
        color: "Natural",
    },
    {
        sku: 1003,
        categoria: "Alimentos",
        nombre: "Envase Rombos",
        material: "PET",
        capacidad: "450 ml",
        cuello: "28 mm",
        proveedor: "SoluPlast",
        lote: "7898",
        cantidad: 200,
        color: "Natural",
    },
    {
        sku: 1004,
        categoria: "Alimentos",
        nombre: "Cilindricos Vinagre",
        material: "PET",
        capacidad: "330 ml",
        cuello: "28 mm",
        proveedor: "SoluPlast",
        lote: "2222",
        cantidad: 500,
        color: "Natural",
    },
    {
        sku: 1005,
        categoria: "Alimentos",
        nombre: "Bombonera",
        material: "PET",
        capacidad: "1000 ml",
        cuello: "120 mm",
        proveedor: "SoluPlast",
        lote: "1245",
        cantidad: 120,
        color: "Natural",
    },
    {
        sku: 1006,
        categoria: "Alimentos",
        nombre: "Envase Biselado",
        material: "PET",
        capacidad: "1000 ml",
        cuello: "28 mm",
        proveedor: "SoluPlast",
        lote: "1246",
        cantidad: 30,
        color: "Blanco",
    },
    {
        sku: 1007,
        categoria: "Alimentos",
        nombre: "Tipo Balas",
        material: "PET",
        capacidad: "250 ml",
        cuello: "28 mm",
        proveedor: "SoluPlast",
        lote: "1111",
        cantidad: 100,
        color: "Natural",
    },
    {
        sku: 1008,
        categoria: "Alimentos",
        nombre: "Enavse Cuadrado con Manija",
        material: "PET",
        capacidad: "3000 ml",
        cuello: "28 mm",
        proveedor: "SoluPlast",
        lote: "9999",
        cantidad: 20,
        color: "Natural",
    },
    {
        sku: 1009,
        categoria: "Alimentos",
        nombre: "Anillado con Asa",
        material: "PET",
        capacidad: "1900 ml",
        cuello: "28 mm",
        proveedor: "SoluPlast",
        lote: "7777",
        cantidad: 520,
        color: "Natural",
    },
    {
        sku: 1010,
        categoria: "Alimentos",
        nombre: "Anillado Alto con Asa",
        material: "PET",
        capacidad: "3000 ml",
        cuello: "38 mm",
        proveedor: "SoluPlast",
        lote: "5050",
        cantidad: 80,
        color: "Natural",
    },
    {
        sku: 1011,
        categoria: "Alimentos",
        nombre: "Anillado 1.000 ml",
        material: "PET",
        capacidad: "1000 ml",
        cuello: "28 mm",
        proveedor: "Otorgo Envases",
        lote: "1212",
        cantidad: 700,
        color: "Natural",
    },
    {
        sku: 1012,
        categoria: "Aseo",
        nombre: "Envase Ref 1",
        material: "POLIETILENO",
        capacidad: "120 ml",
        cuello: "24 mm",
        proveedor: "Otorgo Envases",
        lote: "A6291",
        cantidad: 187,
        color: "Natural",
    },
    {
        sku: 1013,
        categoria: "Aseo",
        nombre: "Envase Ref 2",
        material: "POLIETILENO",
        capacidad: "300 ml",
        cuello: "28 mm",
        proveedor: "Otorgo Envases",
        lote: "A6437",
        cantidad: 214,
        color: "Natural",
    },
    {
        sku: 1014,
        categoria: "Aseo",
        nombre: "Envase Ref 3",
        material: "POLIETILENO",
        capacidad: "400 ml",
        cuello: "24 mm",
        proveedor: "Otorgo Envases",
        lote: "C6803",
        cantidad: 142,
        color: "Blanco",
    },
    {
        sku: 1015,
        categoria: "Aseo",
        nombre: "Envase Ref 4",
        material: "POLIETILENO",
        capacidad: "450 ml",
        cuello: "24 mm",
        proveedor: "Otorgo Envases",
        lote: "C6367",
        cantidad: 220,
        color: "Natural",
    },
    {
        sku: 1016,
        categoria: "Aseo",
        nombre: "Envase Ref 5",
        material: "POLIETILENO",
        capacidad: "500 ml",
        cuello: "28 mm",
        proveedor: "Otorgo Envases",
        lote: "B6831",
        cantidad: 159,
        color: "Blanco",
    },

    {
        sku: 1017,
        categoria: "Aseo",
        nombre: "Envase Ref 6",
        material: "POLIETILENO",
        capacidad: "500 ml",
        cuello: "28 mm",
        proveedor: "Otorgo Envases",
        lote: "B6920",
        cantidad: 178,
        color: "Natural",
    },
    {
        sku: 1018,
        categoria: "Aseo",
        nombre: "Envase Ref 7",
        material: "POLIETILENO",
        capacidad: "1000 ml",
        cuello: "28 mm",
        proveedor: "Otorgo Envases",
        lote: "A6004",
        cantidad: 209,
        color: "Natural",
    },
    {
        sku: 1019,
        categoria: "Aseo",
        nombre: "Envase Ref 8",
        material: "POLIETILENO",
        capacidad: "1200 ml",
        cuello: "28 mm",
        proveedor: "Otorgo Envases",
        lote: "B6341",
        cantidad: 167,
        color: "Natural",
    },
    {
        sku: 1020,
        categoria: "Aseo",
        nombre: "Envase Ref 9",
        material: "POLIETILENO",
        capacidad: "1000 ml",
        cuello: "28 mm",
        proveedor: "Otorgo Envases",
        lote: "B6344",
        cantidad: 210,
        color: "Natural",
    },
    {
        sku: 1021,
        categoria: "Aseo",
        nombre: "Envase Ref 10",
        material: "POLIETILENO",
        capacidad: "450 ml",
        cuello: "28 mm",
        proveedor: "Otorgo Envases",
        lote: "A6947",
        cantidad: 147,
        color: "Blanco",
    },
    {
        sku: 1022,
        categoria: "Cosmetico",
        nombre: "Envase Shampoo",
        material: "PET",
        capacidad: "400 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L12",
        cantidad: 50,
        color: "Natural",
    },
    {
        sku: 1023,
        categoria: "Cosmetico",
        nombre: "Envase Humectante",
        material: "PEAD",
        capacidad: "100 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L40",
        cantidad: 30,
        color: "Natural",
    },
    {
        sku: 1024,
        categoria: "Cosmetico",
        nombre: "Envase Colonia",
        material: "PET",
        capacidad: "200 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L85",
        cantidad: 200,
        color: "Natural",
    },
    {
        sku: 1025,
        categoria: "Cosmetico",
        nombre: "Envase Splash",
        material: "PET",
        capacidad: "120 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L21",
        cantidad: 150,
        color: "Natural",
    },
    {
        sku: 1026,
        categoria: "Cosmetico",
        nombre: "Envase Chamaco",
        material: "PEAD",
        capacidad: "250 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L89",
        cantidad: 650,
        color: "Natural",
    },
    {
        sku: 1027,
        categoria: "Cosmetico",
        nombre: "Envase Crema",
        material: "PEAD",
        capacidad: "400 ml",
        cuello: "24 mm",
        proveedor: "Coenplas",
        lote: "L98",
        cantidad: 400,
        color: "Natural",
    },
    {
        sku: 1028,
        categoria: "Cosmetico",
        nombre: "Envase Cosmético",
        material: "PET",
        capacidad: "600 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L36",
        cantidad: 220,
        color: "Blanco",
    },
    {
        sku: 1029,
        categoria: "Cosmetico",
        nombre: "Envase Peroxido",
        material: "PEAD",
        capacidad: "120 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L87",
        cantidad: 100,
        color: "Natural",
    },
    {
        sku: 1030,
        categoria: "Cosmetico",
        nombre: "Envase Talquera",
        material: "PEAD",
        capacidad: "200 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L45",
        cantidad: 50,
        color: "Blanco",
    },
    {
        sku: 1031,
        categoria: "Cosmetico",
        nombre: "Envase Pote",
        material: "PEAD",
        capacidad: "300 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L50",
        cantidad: 30,
        color: "Natural",
    },
    {
        sku: 1032,
        categoria: "Cosmetico",
        nombre: "Envase Colonia Tipo Bala",
        material: "PET",
        capacidad: "120 ml",
        cuello: "28 mm",
        proveedor: "Coenplas",
        lote: "L23",
        cantidad: 15,
        color: "Natural",
    },
    {
        sku: 1033,
        categoria: "Farmaceutico",
        nombre: "Envase Farma",
        material: "PEAD",
        capacidad: "120 ml",
        cuello: "28 mm",
        proveedor: "Plasti Valle",
        lote: "294PV",
        cantidad: 110,
        color: "Natural",
    },
    {
        sku: 1034,
        categoria: "Farmaceutico",
        nombre: "Envase Farma",
        material: "PEAD",
        capacidad: "60 ml",
        cuello: "24 mm",
        proveedor: "Plasti Valle",
        lote: "292PV",
        cantidad: 100,
        color: "Natural",
    },
    {
        sku: 1035,
        categoria: "Farmaceutico",
        nombre: "Envase Jarabero",
        material: "PEAD",
        capacidad: "120 ml",
        cuello: "28 mm",
        proveedor: "Plasti Valle",
        lote: "298PV",
        cantidad: 93,
        color: "Natural",
    },
    {
        sku: 1036,
        categoria: "Farmaceutico",
        nombre: "Envase Jarabero",
        material: "PEAD",
        capacidad: "90 ml",
        cuello: "24 mm",
        proveedor: "Plasti Valle",
        lote: "334PV",
        cantidad: 202,
        color: "Natural",
    },
    {
        sku: 1037,
        categoria: "Farmaceutico",
        nombre: "Envase Jarabero",
        material: "PEAD",
        capacidad: "60 ml",
        cuello: "24 mm",
        proveedor: "Plasti Valle",
        lote: "336PV",
        cantidad: 150,
        color: "Natural",
    },
    {
        sku: 1038,
        categoria: "Farmaceutico",
        nombre: "Envase Jarabero Tapa Azul",
        material: "PET",
        capacidad: "90 ml",
        cuello: "24 mm",
        proveedor: "Plasti Valle",
        lote: "315PV",
        cantidad: 198,
        color: "Natural",
    },
    {
        sku: 1039,
        categoria: "Farmaceutico",
        nombre: "Envase Jarabero Tapa Amarilla",
        material: "PET",
        capacidad: "60 ml",
        cuello: "24 mm",
        proveedor: "Plasti Valle",
        lote: "343PV",
        cantidad: 265,
        color: "Natural",
    },
    {
        sku: 1040,
        categoria: "Farmaceutico",
        nombre: "Envase Bucal",
        material: "PET",
        capacidad: "250 ml",
        cuello: "28 mm",
        proveedor: "Plasti Valle",
        lote: "341PV",
        cantidad: 220,
        color: "Natural",
    },
    {
        sku: 1041,
        categoria: "Farmaceutico",
        nombre: "Envase Bucal",
        material: "PET",
        capacidad: "300 ml",
        cuello: "28 mm",
        proveedor: "Plasti Valle",
        lote: "324PV",
        cantidad: 216,
        color: "Natural",
    },
    {
        sku: 1042,
        categoria: "Farmaceutico",
        nombre: "Envase Bucal",
        material: "PET",
        capacidad: "400 ml",
        cuello: "28 mm",
        proveedor: "Plasti Valle",
        lote: "250PV",
        cantidad: 255,
        color: "Natural",
    },
    {
        sku: 1043,
        categoria: "Bebidas",
        nombre: "Envase Redondo",
        material: "PET",
        capacidad: "5000 ml",
        cuello: "46 mm",
        proveedor: "Multiplast",
        lote: "RJ87S",
        cantidad: 187,
        color: "Blanco",
    },
    {
        sku: 1044,
        categoria: "Bebidas",
        nombre: "Envase Boca",
        material: "PET",
        capacidad: "5000 ml",
        cuello: "46 mm",
        proveedor: "Multiplast",
        lote: "RJ50S",
        cantidad: 189,
        color: "Natural",
    }
    ,
    {
        sku: 1045,
        categoria: "Bebidas",
        nombre: "Envase Galon",
        material: "PEAD",
        capacidad: "3785 ml",
        cuello: "38 mm",
        proveedor: "Multiplast",
        lote: "RJ26A",
        cantidad: 163,
        color: "Blanco",
    },
    {
        sku: 1046,
        categoria: "Bebidas",
        nombre: "Envase Galon Lacteos",
        material: "PEAD",
        capacidad: "3785 ml",
        cuello: "38 mm",
        proveedor: "Multiplast",
        lote: "RJ78B",
        cantidad: 86,
        color: "Natural",
    },
    {
        sku: 1047,
        categoria: "Bebidas",
        nombre: "Envase Galon Multiusos",
        material: "PET",
        capacidad: "3000 ml",
        cuello: "38 mm",
        proveedor: "Multiplast",
        lote: "RJ12S",
        cantidad: 170,
        color: "Natural",
    },
    {
        sku: 1048,
        categoria: "Bebidas",
        nombre: "Envase Carbonatados",
        material: "PET",
        capacidad: "3020 ml",
        cuello: "28 mm",
        proveedor: "Multiplast",
        lote: "RJ30B",
        cantidad: 199,
        color: "Natural",
    },
    {
        sku: 1049,
        categoria: "Bebidas",
        nombre: "Envase con Agarre",
        material: "PEAD",
        capacidad: "1850 ml",
        cuello: "36 mm",
        proveedor: "Multiplast",
        lote: "RJ89B",
        cantidad: 168,
        color: "Blanco",
    },
    {
        sku: 1050,
        categoria: "Bebidas",
        nombre: "Envase Bebida Tipo Bala",
        material: "PET",
        capacidad: "750 ml",
        cuello: "28 mm",
        proveedor: "Multiplast",
        lote: "RJ45A",
        cantidad: 162,
        color: "Azul",
    },
    {
        sku: 1051,
        categoria: "Bebidas",
        nombre: "Envase sin Agarre",
        material: "PET",
        capacidad: "520 ml",
        cuello: "46 mm",
        proveedor: "Multiplast",
        lote: "RJ46B",
        cantidad: 12,
        color: "Blanco",
    },
    {
        sku: 1052,
        categoria: "Bebidas",
        nombre: "Envase Bucal Tipo Bala",
        material: "PET",
        capacidad: "750 ml",
        cuello: "28 mm",
        proveedor: "Multiplast",
        lote: "RJ10S",
        cantidad: 100,
        color: "Natural",
    }
];